services:
  db:
    image: mysql:8.0
    container_name: app_db
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./services/db/init:/docker-entrypoint-initdb.d
      - ./services/db/my.cnf:/etc/mysql/conf.d/my.cnf

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent", "-u", "root", "-p${MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app_phpmyadmin
    ports:
      - "8081:80"
    env_file:
      - .env
    environment:
      PMA_HOST: db
    depends_on:
      - db

  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    container_name: app_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    container_name: app_web
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - api

volumes:
  db_data:
