# docker-compose.yml

services:
  db:
    image: mysql:8.0
    container_name: app_db
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      # Se você tiver scripts de inicialização no host, ajuste o caminho abaixo:
      - ./services/api/app/db/init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app_phpmyadmin
    ports:
      - "8081:80"
    env_file:
      - .env
    environment:
      PMA_HOST: db
    depends_on:
      - db

  api:
    build:
      context: ./services/api        # aponta para a pasta que contém o Dockerfile da API
      dockerfile: Dockerfile
    container_name: app_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      # Monta todo o código-fonte no container para hot-reload
      - ./services/api/app:/app

  web:
    build:
      context: ./services/web        # aponta para a pasta que contém o Dockerfile do Next.js
      dockerfile: Dockerfile
    container_name: app_web
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - api
    volumes:
      # Monta todo o código-fonte do Next.js no container para hot-reload
      - ./services/web/app:/usr/src/app

volumes:
  db_data:
