version: "3.8"

services:
  # -----------------------
  # Banco de dados MySQL
  # -----------------------
  db:
    image: mysql:8.0
    container_name: ualg_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: cantina
      MYSQL_USER: staff_user
      MYSQL_PASSWORD: ${MYSQL_STAFF_PASSWORD:-staff_pass}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d  # scripts de inicialização (schema, users, dados de teste)
    ports:
      - "3306:3306"
    command: --log-error-verbosity=3  # nível máximo de detalhes de log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # -----------------------
  # Interface de administração do BD
  # -----------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ualg_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      UPLOAD_LIMIT: 300M
    depends_on:
      - db
    ports:
      - "8080:80"  # http://localhost:8080

  # -----------------------
  # API FastAPI
  # -----------------------
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ualg_api
    restart: unless-stopped
    volumes:
      - ./api:/app  # permite hot-reload com código local
    env_file:
      - ./api/.env  # inclui URLs do banco + auth configs
    depends_on:
      - db
    ports:
      - "8000:8000"  # http://localhost:8000/docs

# Definição dos volumes nomeados
volumes:
  db_data:
#     driver: local
