-- db/init/001_create_tables.sql

USE cantina;

-- 1) Tabela de alergénios
CREATE TABLE IF NOT EXISTS alergenos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2) Tabela de pratos
CREATE TABLE IF NOT EXISTS pratos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  designacao VARCHAR(255) NOT NULL,
  alergeno_id INT NOT NULL,
  FOREIGN KEY (alergeno_id) REFERENCES alergenos(id)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3) Tabela de ementas
CREATE TABLE IF NOT EXISTS ementas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  data DATE NOT NULL,
  prato_id INT NOT NULL,
  FOREIGN KEY (prato_id) REFERENCES pratos(id)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
