version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: app_db
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # Assuming DB_PASSWORD in .env is root password
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD} # Using same password for simplicity, adjust as needed

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app_phpmyadmin
    ports:
      - "8081:80"
    env_file:
      - .env
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # Use root password to connect to db
    depends_on:
      - db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: app_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    # Optional: Volume for live code reloading during development
    # volumes:
      - ./api/app:/api/app

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: app_web
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - api
    # Optional: Volume for live code reloading during development
    # volumes:
      - ./web/app:/web/app

volumes:
  db_data: