version: '3.9'
services:
  web:  # frontend jรก existente
    build: ./web
    ports: ["3000:80"]
  api:
    build: ./api
    ports: ["8000:8000"]
    env_file: ../.env
    depends_on: [db]
  db:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: ementas
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    image: phpmyadmin
    ports: ["8081:80"]
    environment:
      PMA_HOST: db