# Use a imagem oficial do MySQL como base
FROM mysql:8.0

# Copie o arquivo customizado de configuração do MySQL (opcional)
COPY my.cnf /etc/mysql/conf.d/my.cnf

# Copie scripts SQL adicionais ou scripts shell, se necessário
# COPY init /docker-entrypoint-initdb.d

